### ISSUE TITLE
Keywords in documentation not corresponding to the code 

### ISSUE THREAD

**Issue by SchDvr** [cb-geo/mpm-doc#54]
**Bug description**
In the [user's documentation](https://github.com/cb-geo/mpm-doc/blob/master/user/preprocess/input.md) the keywords used to set the damping and the mpm scheme are not the same as in the code:
 - `stress_update` in the documentation should be `mpm_scheme` (see [this line](https://github.com/cb-geo/mpm/blob/c9630b300f18d5cde87945e7f1ae8d1e7040d1cc/include/solvers/mpm_base.tcc#L55) in the code)
 - `damping_ratio` in the documentation should be `damping_factor` (see [this line](https://github.com/cb-geo/mpm/blob/c9630b300f18d5cde87945e7f1ae8d1e7040d1cc/include/solvers/mpm_base.tcc#L1123) in the code)

Beside not specifying the damping doesn't trigger a warning, but [here](https://github.com/cb-geo/mpm/blob/c9630b300f18d5cde87945e7f1ae8d1e7040d1cc/include/solvers/mpm_base.tcc#L82) it looks like it should. I think it's because of [this if](https://github.com/cb-geo/mpm/blob/c9630b300f18d5cde87945e7f1ae8d1e7040d1cc/include/solvers/mpm_base.tcc#L77): if no damping is specified no error occurs so [this catch](https://github.com/cb-geo/mpm/blob/c9630b300f18d5cde87945e7f1ae8d1e7040d1cc/include/solvers/mpm_base.tcc#L81) never runs. 
But maybe it would be better to open an issue on cb-geo/mpm for this problem?

**Comment by jgiven100** [comment]
Thanks for catching the differences `mpm_scheme` and `damping_factor`
I've opened a PR (https://github.com/cb-geo/mpm-doc/pull/55) to update the naming in our documentation

**Comment by jgiven100** [comment]
@SchDvr As for the damping warning, it might be ok as is [L75-L84](https://github.com/cb-geo/mpm/blob/c9630b300f18d5cde87945e7f1ae8d1e7040d1cc/include/solvers/mpm_base.tcc#L75-L84). 

If no `damping` is specified, then no warning. 
If `damping` is specified but no `damping_factor` is specified, then we get a warning. 

I'm ok with this. What do others think? @kks32  @bodhinandach

**Comment by bodhinandach** [comment]
Thanks, @jgiven100 I agree with you. PR #55 should solve.
